name: Chromatic

on:
  pull_request:
    branches:
      - develop
    types: [labeled, unlabeled, synchronize, opened, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  chromatic-publish:
    if: >
      github.event_name == 'pull_request' &&
      contains(join(github.event.pull_request.labels.*.name, ','), 'ui-review')
    name: ğŸ“š Publish on Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: ğŸ§° Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: ğŸ›  Setup Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: 'pnpm'

      - name: ğŸ§³ Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: âš¡ Turbo cache
        id: turbo-cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ runner.os }}-${{ github.ref_name }}

      - name: ğŸ“¦ Install dependencies
        run: pnpm install

      - name: ğŸ‘·ğŸ»â€â™€ï¸ Build
        id: run-build
        run: pnpm run build:ci

      - name: ğŸ“š Publish Storybook to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: 'storybook-static'
          workingDir: 'apps/docs'
          zip: true
          exitOnceUploaded: true
          exitZeroOnChanges: true
